import { chromium, firefox, webkit } from "playwright";
import { writeFile, mkdir, rm } from "fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { randomUUID } from "crypto";

export class PlaywrightRunner {
  async runScript(script, options = {}) {
    const { browser: browserType = "chromium", headless = true, url } = options;
    const browser = await this._launchBrowser(browserType, headless);

    try {
      const context = await browser.newContext();
      const page = await context.newPage();
      if (url) await page.goto(url);

      // Execute the script in the page context
      const result = await this._executeScript(page, script, url);
      await context.close();
      return result;
    } finally {
      await browser.close();
    }
  }

  async runGherkin(feature, options = {}) {
    const { url, browser: browserType = "chromium", headless = true, recordVideo = false, takeScreenshots = true } = options;
    const runId = randomUUID();
    const outputDir = join(tmpdir(), `qa-orchestrator-${runId}`);
    await mkdir(outputDir, { recursive: true });

    const browser = await this._launchBrowser(browserType, headless);
    const results = { feature, scenarios: [], outputDir, passed: 0, failed: 0, screenshots: [] };

    try {
      const scenarios = this._parseGherkin(feature);

      for (const scenario of scenarios) {
        const contextOptions = {};
        if (recordVideo) contextOptions.recordVideo = { dir: join(outputDir, "videos") };

        const context = await browser.newContext(contextOptions);
        const page = await context.newPage();
        const scenarioResult = { name: scenario.name, steps: [], status: "passed" };

        if (url) {
          await page.goto(url).catch(() => {});
        }

        for (const step of scenario.steps) {
          const stepResult = await this._executeGherkinStep(page, step, url);
          scenarioResult.steps.push(stepResult);

          if (takeScreenshots && stepResult.status !== "skipped") {
            const screenshotPath = join(outputDir, `${scenario.name.replace(/\s+/g, "_")}_step${scenarioResult.steps.length}.png`);
            await page.screenshot({ path: screenshotPath, fullPage: false }).catch(() => {});
            results.screenshots.push(screenshotPath);
          }

          if (stepResult.status === "failed") {
            scenarioResult.status = "failed";
          }
        }

        if (scenarioResult.status === "passed") results.passed++;
        else results.failed++;

        results.scenarios.push(scenarioResult);
        await context.close();
      }
    } finally {
      await browser.close();
    }

    return {
      summary: `${results.passed} passed, ${results.failed} failed out of ${results.scenarios.length} scenarios`,
      results,
    };
  }

  generateScriptFromTC(testCase, baseUrl) {
    const steps = testCase.steps || testCase.testScript?.steps || [];
    const name = testCase.name || "Generated Test";

    const lines = [
      `// Generated by qa-orchestrator-mcp`,
      `// Test Case: ${name}`,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test('${name.replace(/'/g, "\\'")}', async ({ page }) => {`,
      `  // Base URL: ${baseUrl || "configure in playwright.config.ts"}`,
      baseUrl ? `  await page.goto('${baseUrl}');` : `  // TODO: navigate to the correct URL`,
      ``,
    ];

    for (let i = 0; i < steps.length; i++) {
      const step = steps[i];
      const desc = step.description || step.action || `Step ${i + 1}`;
      const expected = step.expectedResult || step.expected_result || "";
      const testData = step.testData || step.test_data || "";

      lines.push(`  // Step ${i + 1}: ${desc}`);
      if (testData) lines.push(`  // Test data: ${testData}`);

      // Generate Playwright actions based on step description keywords
      const stepCode = this._stepToPlaywright(desc, testData, expected, i);
      lines.push(stepCode);

      if (expected) {
        lines.push(`  // Expected: ${expected}`);
      }
      lines.push(``);
    }

    lines.push(`});`);
    return lines.join("\n");
  }

  async accessibilityAudit(url, wcagLevel = "AA") {
    const browser = await chromium.launch({ headless: true });
    try {
      const context = await browser.newContext();
      const page = await context.newPage();
      await page.goto(url, { waitUntil: "networkidle" });

      // Inject axe-core for accessibility testing
      await page.addScriptTag({ url: "https://cdnjs.cloudflare.com/ajax/libs/axe-core/4.8.2/axe.min.js" });

      const wcagTags = {
        A: ["wcag2a"],
        AA: ["wcag2a", "wcag2aa"],
        AAA: ["wcag2a", "wcag2aa", "wcag2aaa"],
      }[wcagLevel] || ["wcag2a", "wcag2aa"];

      const results = await page.evaluate((tags) => {
        return new Promise((resolve) => {
          window.axe.run({ runOnly: { type: "tag", values: tags } }, (err, results) => {
            resolve(err ? { error: err.message } : results);
          });
        });
      }, wcagTags);

      await context.close();

      return {
        url,
        wcagLevel,
        violations: (results.violations || []).map((v) => ({
          id: v.id,
          impact: v.impact,
          description: v.description,
          nodes: v.nodes?.length || 0,
          help: v.help,
          helpUrl: v.helpUrl,
        })),
        passes: results.passes?.length || 0,
        inapplicable: results.inapplicable?.length || 0,
        summary: `${results.violations?.length || 0} violations, ${results.passes?.length || 0} passes (WCAG ${wcagLevel})`,
      };
    } finally {
      await browser.close();
    }
  }

  async visualSnapshot(url, options = {}) {
    const { fullPage = true, mobile = false, device } = options;
    const browser = await chromium.launch({ headless: true });

    try {
      const contextOptions = {};

      if (device) {
        // Map common device names
        const devices = {
          "iPhone 15 Pro Max": { viewport: { width: 430, height: 932 }, userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15" },
          "iPad Pro": { viewport: { width: 1024, height: 1366 } },
          "Pixel 7": { viewport: { width: 412, height: 915 } },
        };
        Object.assign(contextOptions, devices[device] || { viewport: { width: 375, height: 812 } });
      } else if (mobile) {
        contextOptions.viewport = { width: 375, height: 812 };
      } else {
        contextOptions.viewport = { width: 1920, height: 1080 };
      }

      const context = await browser.newContext(contextOptions);
      const page = await context.newPage();
      await page.goto(url, { waitUntil: "networkidle" });

      const screenshotPath = join(tmpdir(), `snapshot_${Date.now()}.png`);
      const screenshot = await page.screenshot({ path: screenshotPath, fullPage });

      const base64 = screenshot.toString("base64");
      await context.close();

      return {
        url,
        viewport: contextOptions.viewport,
        device: device || (mobile ? "mobile" : "desktop"),
        fullPage,
        screenshotBase64: base64.substring(0, 100) + "... [truncated for display]",
        screenshotPath,
        message: "Screenshot captured successfully",
      };
    } finally {
      await browser.close();
    }
  }

  // ─── Private helpers ──────────────────────────────────────────────────────────

  async _launchBrowser(type, headless) {
    const launcher = { chromium, firefox, webkit }[type] || chromium;
    return launcher.launch({ headless });
  }

  async _executeScript(page, script, baseUrl) {
    // Wrap the script in a try/catch and execute it
    try {
      const wrappedScript = `
        (async () => {
          ${script}
        })();
      `;
      await page.evaluate(wrappedScript);
      return { status: "passed", message: "Script executed successfully" };
    } catch (err) {
      return { status: "failed", error: err.message };
    }
  }

  async _executeGherkinStep(page, step, baseUrl) {
    const { keyword, text } = step;
    const result = { keyword, text, status: "passed", duration: 0 };
    const start = Date.now();

    try {
      // Map common Gherkin patterns to Playwright actions
      if (/está autenticado|logged in|accede con/i.test(text)) {
        // Authentication step - navigate to login
        if (baseUrl) await page.goto(baseUrl).catch(() => {});
        result.message = "Navigation to base URL";
      } else if (/navega a|goes to|abre|opens/i.test(text)) {
        const urlMatch = text.match(/"([^"]+)"|'([^']+)'/);
        if (urlMatch) {
          const target = urlMatch[1] || urlMatch[2];
          if (target.startsWith("http")) {
            await page.goto(target);
          } else {
            await page.goto(`${baseUrl}/${target.replace(/^\//, "")}`).catch(() => {});
          }
        }
        result.message = "Navigated";
      } else if (/hace click|clicks|pulsa|selecciona/i.test(text)) {
        const target = text.match(/"([^"]+)"|'([^']+)'/)?.[1];
        if (target) {
          await page.getByText(target).first().click({ timeout: 5000 }).catch(() =>
            page.locator(`[aria-label="${target}"]`).click({ timeout: 3000 }).catch(() => {})
          );
        }
        result.message = "Click attempted";
      } else if (/introduce|rellena|escribe|enters|fills/i.test(text)) {
        const valueMatch = text.match(/"([^"]+)"/g);
        if (valueMatch?.length >= 2) {
          const field = valueMatch[0].replace(/"/g, "");
          const value = valueMatch[1].replace(/"/g, "");
          await page.getByLabel(field).fill(value, { timeout: 3000 }).catch(() =>
            page.getByPlaceholder(field).fill(value, { timeout: 3000 }).catch(() => {})
          );
        }
        result.message = "Text input attempted";
      } else if (/verifica|comprueba|debe mostrar|should see|espera/i.test(text)) {
        const target = text.match(/"([^"]+)"|'([^']+)'/)?.[1];
        if (target) {
          await page.waitForSelector(`text=${target}`, { timeout: 5000 }).catch(() => {
            result.status = "failed";
            result.error = `Element with text "${target}" not found`;
          });
        }
        result.message = "Assertion attempted";
      } else {
        result.status = "skipped";
        result.message = "Step pattern not matched - manual execution required";
      }
    } catch (err) {
      result.status = "failed";
      result.error = err.message;
    }

    result.duration = Date.now() - start;
    return result;
  }

  _parseGherkin(feature) {
    const scenarios = [];
    const lines = feature.split("\n");
    let currentScenario = null;

    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed.startsWith("Scenario:") || trimmed.startsWith("Scenario Outline:")) {
        if (currentScenario) scenarios.push(currentScenario);
        currentScenario = { name: trimmed.replace(/^Scenario(?: Outline)?:\s*/, ""), steps: [] };
      } else if (currentScenario && /^(Given|When|Then|And|But)\s/.test(trimmed)) {
        const [keyword, ...rest] = trimmed.split(" ");
        currentScenario.steps.push({ keyword, text: rest.join(" ") });
      }
    }

    if (currentScenario) scenarios.push(currentScenario);
    return scenarios;
  }

  _stepToPlaywright(description, testData, expected, index) {
    const desc = description.toLowerCase();

    if (/naveg|ve a|goto|abre|accede/i.test(desc)) {
      return `  await page.goto('/* TODO: URL */');`;
    }
    if (/hace click|click|pulsa|presiona/i.test(desc)) {
      return `  await page.getByRole('button', { name: '/* TODO: button name */' }).click();`;
    }
    if (/escribe|introduce|rellena|fill/i.test(desc)) {
      return `  await page.getByLabel('/* TODO: label */').fill('${testData || "/* TODO: value */"}');`;
    }
    if (/verifica|comprueba|debe|visible|muestra/i.test(desc)) {
      return `  await expect(page.getByText('/* TODO: expected text */')).toBeVisible();`;
    }
    if (/espera|wait/i.test(desc)) {
      return `  await page.waitForLoadState('networkidle');`;
    }
    if (/selecciona|elige|dropdown/i.test(desc)) {
      return `  await page.selectOption('/* TODO: selector */', '/* TODO: value */');`;
    }

    return `  // TODO: implement step - "${description}"`;
  }
}
